default scatter style: SQUARE
default max attempts per player: 250
default teleports per set: 5
default ticks between sets: 20
default minimum radius: 0
allowed blocks:
- DIRT
- LEAVES
- LEAVES_2
- SAND
- STONE
- GRAVEL
- SNOW
- SNOW_BLOCK
- ICE
- GRASS
- LOG
- LOG_2
- DOUBLE_PLANT
- DEAD_BUSH
- CROPS
- LONG_GRASS
- SANDSTONE
- VINE
- WATER_LILY
- WHEAT
- STAINED_CLAY